/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import BOs.NegocioFachada;
import Entidades.LineaInvestigacion;
import Entidades.Proyecto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulina Cortez Alamilla.
 */
public class FrmBuscarProyecto extends javax.swing.JFrame {

    
    NegocioFachada negFac;
    /**
     * Creates new form PantallaProyectos
     */
    public FrmBuscarProyecto() {
        initComponents();
        negFac=new NegocioFachada();
        dateInicio.setEnabled(false);
        dateFinal.setEnabled(false);
        txtCampoBuscar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCampoBuscar = new javax.swing.JTextField();
        fInicio = new javax.swing.JLabel();
        fFinal = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jscroll = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        proyecto = new javax.swing.JLabel();
        opcionComboBox = new javax.swing.JComboBox<>();
        dateInicio = new com.github.lgooddatepicker.components.DatePicker();
        dateFinal = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar proyecto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar Proyecto");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, -1, -1));
        getContentPane().add(txtCampoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, 188, -1));

        fInicio.setText("Fecha inicio:");
        fInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(fInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 55, -1, -1));

        fFinal.setText("Fecha finalización:");
        fFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(fFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 55, -1, -1));

        botonBuscar.setText("Buscar");
        botonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 439, 78, 42));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Acrónimo ", "Programa", "Fecha inicio", "Fecha fin"
            }
        ));
        jscroll.setViewportView(tbl);

        getContentPane().add(jscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 195, 887, 232));

        proyecto.setText("Proyecto");
        proyecto.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        getContentPane().add(proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, -1, -1));

        opcionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre", "Acronimo", "Programa de Investigacion", "Periodo" }));
        opcionComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        opcionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(opcionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 52, 188, -1));
        getContentPane().add(dateInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 83, -1, -1));
        getContentPane().add(dateFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 83, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if(opcionComboBox.getSelectedItem()== "Codigo"){
            setTablaProyectos();
        }
        if(opcionComboBox.getSelectedItem()== "Nombre"){
           setTablaProyectos();
        }
        if(opcionComboBox.getSelectedItem()== "Acronimo"){
            
            
        }
        if(opcionComboBox.getSelectedItem()== "Programa de Investigacion"){
           
            
        }
        if(opcionComboBox.getSelectedItem()== "Periodo"){
            
            
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void opcionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionComboBoxActionPerformed
        /*
        Codigo
        Nombre
        Acronimo
        Programa de Investigacion
        */
        
        if(opcionComboBox.getSelectedItem()== "Codigo"){
            proyecto.setText("Proyectos");
            dateInicio.setEnabled(false);
            dateFinal.setEnabled(false);
            txtCampoBuscar.setVisible(true);
            clear();
        }
        if(opcionComboBox.getSelectedItem()== "Nombre"){
            proyecto.setText("Proyectos");
            dateInicio.setEnabled(false);
            dateFinal.setEnabled(false);
            txtCampoBuscar.setVisible(true);
            clear();
        }
        if(opcionComboBox.getSelectedItem()== "Acronimo"){
            proyecto.setText("Proyectos");
            dateInicio.setEnabled(false);
            dateFinal.setEnabled(false);
            txtCampoBuscar.setVisible(true);
            clear();
        }
        if(opcionComboBox.getSelectedItem()== "Programa de Investigacion"){
            proyecto.setText("Programas de Investigación");
            dateInicio.setEnabled(false);
            dateFinal.setEnabled(false);
            txtCampoBuscar.setVisible(true);
            
            setTablaProgramas();
            
        }
        if(opcionComboBox.getSelectedItem()== "Periodo"){
            proyecto.setText("Proyectos");
            dateInicio.setEnabled(true);
            dateFinal.setEnabled(true);
            txtCampoBuscar.setVisible(true);
            txtCampoBuscar.setVisible(false);
            clear();
        }
        
        

    }//GEN-LAST:event_opcionComboBoxActionPerformed

    public void setTablaProgramas(){
        List<LineaInvestigacion> listLinInv = negFac.consultarTodosLinInv();
        
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int rowCount = model.getRowCount();
        
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
          model.removeRow(i);
        }
        
        Object rowData[]=new Object[1];
        for(int i=0; i <listLinInv.size();i++){
            rowData[0]=listLinInv.get(i);
            model.addRow(rowData);
        }
    }
    
    public void setTablaProyectos(){
        List<Proyecto> list;
        if(opcionComboBox.getSelectedItem()== "Codigo"){
            list = negFac.consultarProyectoCodigo(txtCampoBuscar.getText());
        }
        else if(opcionComboBox.getSelectedItem()== "Nombre"){
            list = negFac.consultarProyectoNombre(txtCampoBuscar.getText());
        }
        else if(opcionComboBox.getSelectedItem()== "Acronimo"){
            list = negFac.consultarProyectoAcronimo(txtCampoBuscar.getText());
        }
        else if(opcionComboBox.getSelectedItem()== "Programa de Investigacion"){
            list = negFac.consultarProyectoPrograma(txtCampoBuscar.getText());
        }
        else{
            list = negFac.consultarTodosProyectos();
        }
        
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int rowCount = model.getRowCount();
        
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
          model.removeRow(i);
        }
        
        Object rowData[]=new Object[6];
        for(int i=0; i <list.size();i++){
            rowData[0]=list.get(i).getCodigo();
            rowData[1]=list.get(i).getNombre();
            rowData[2]=list.get(i).getAcronimo();
            rowData[3]=list.get(i).getProgramaInvestigacion().getNombre();
            rowData[4]=list.get(i).getFechaInicio();
            rowData[5]=list.get(i).getFechaFin();
            model.addRow(rowData);
        }
    }
    
    public void clear(){
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int rowCount = model.getRowCount();
        
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
          model.removeRow(i);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private com.github.lgooddatepicker.components.DatePicker dateFinal;
    private com.github.lgooddatepicker.components.DatePicker dateInicio;
    private javax.swing.JLabel fFinal;
    private javax.swing.JLabel fInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jscroll;
    private javax.swing.JComboBox<String> opcionComboBox;
    private javax.swing.JLabel proyecto;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCampoBuscar;
    // End of variables declaration//GEN-END:variables
}
