/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author Vastem
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarProfesor = new javax.swing.JButton();
        btnBuscarProyecto = new javax.swing.JButton();
        btnAgregarPublicacion = new javax.swing.JButton();
        btnRegistrarProyecto = new javax.swing.JButton();
        ea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarProfesor.setText("Registrar profesor");
        btnRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 179, 55));

        btnBuscarProyecto.setText("Buscar proyecto");
        btnBuscarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 179, 54));

        btnAgregarPublicacion.setText("Agregar publicacion");
        btnAgregarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPublicacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 179, 55));

        btnRegistrarProyecto.setText("Registrar proyecto");
        btnRegistrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 179, 54));

        ea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/panorama_3.png"))); // NOI18N
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfesorActionPerformed
        FrmRegistrarProfesor rp = new FrmRegistrarProfesor();
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarProfesorActionPerformed

    private void btnRegistrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProyectoActionPerformed
        FrmRegistrarProyecto pantallaRegistro=new FrmRegistrarProyecto();
        pantallaRegistro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarProyectoActionPerformed

    private void btnBuscarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProyectoActionPerformed
        FrmBuscarProyecto bp = new FrmBuscarProyecto();
        bp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBuscarProyectoActionPerformed

    private void btnAgregarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPublicacionActionPerformed
        FrmAgregarPublicacion ap = new FrmAgregarPublicacion();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarPublicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPublicacion;
    private javax.swing.JButton btnBuscarProyecto;
    private javax.swing.JButton btnRegistrarProfesor;
    private javax.swing.JButton btnRegistrarProyecto;
    private javax.swing.JLabel ea;
    // End of variables declaration//GEN-END:variables
}
